apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/argocd-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  selector:
    # Ye selector ArgoCD ke original pods ko target karega
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32002
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 32003
