apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-redis-data # ArgoCD default yahi naam dhundta hai agar stateful ho
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
