sonarqube:
  edition: community
  # Naye version mein overwrite yahan hota hai
  jdbcOverwrite: true

service:
  type: NodePort
  nodePort: 32001

postgresql:
  enabled: false

# Yeh section seedha root level par rahega
jdbcUrl: "jdbc:postgresql://sonarqube-db.ctisccigc9jk.ap-south-1.rds.amazonaws.com:5432/postgres?sslmode=disable"
jdbcUsername: "sonar"
jdbcPassword: "Zuhaibahmed001100."

persistence:
  enabled: true
  size: 10Gi

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: "500m"
    memory: 1Gi
