# 1. Database Passwords (Direct from Database Engine)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-passwords
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ghost-secrets # Dono ek hi secret mein merge honge
    creationPolicy: Merge
  data:
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: "../../database/static-creds/ghost-root-role"
      property: password
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: "../../database/static-creds/ghost-app-role"
      property: password
---
# 2. KV Metadata (From KV Engine)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-metadata
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ghost-secrets # Merge into the same secret
    creationPolicy: Merge
  data:
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: devsecops/creds
      property: MYSQL_DATABASE
  - secretKey: MYSQL_USER
    remoteRef:
      key: devsecops/creds
      property: MYSQL_USER
