apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost-secrets
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ghost-secrets
    creationPolicy: Owner
  data:
  # 1. Database Passwords (from the Database Engine)
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: database/static-creds/ghost-root-role
      property: password
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: database/static-creds/ghost-app-role
      property: password
  # 2. Database Metadata (from the KV Engine)
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: devsecops/creds
      property: MYSQL_DATABASE
  - secretKey: MYSQL_USER
    remoteRef:
      key: devsecops/creds
      property: MYSQL_USER
