apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  # stringData use karne se aapko base64 manual nahi karna parta
  mysql-root-password: password
  mysql-database: ghost_db
