apiVersion: v1
kind: Secret
metadata:
  name: ghost-secrets   # Isay 'mysql-secrets' se 'ghost-secrets' kar dein
type: Opaque
stringData:
  mysql-root-password: password
  mysql-database: ghost_db
  # Ye niche wali line zaroori hai Ghost ke liye
  database__connection__password: password

