apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: zuhaibahmed034/ghost-devsecops:v1
        env:
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__host # Matches key in Vault
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__user # Matches key in Vault
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__password # Matches key in Vault
        - name: database__connection__database
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__database # Matches key in Vault
