apiVersion: v1
kind: Pod
metadata:
  name: pci-violation-pod
spec:
  containers:
  - name: hacker-container
    image: alpine
    command: ["sleep", "3600"]
    securityContext:
      privileged: true # Ye Gatekeeper ko trigger karega
